version: 0.1.{build}

pull_requests:
  do_not_increment_build_number: true

install:
  appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

platform: Any CPU
configuration: Release

before_build:
  - ps: |
      nuget restore Avior.sln
      $content = (Get-Content Avior/Avior.nuspec) 
      $content = $content -replace '\$version\$',${env:APPVEYOR_BUILD_VERSION}
      $content | Out-File Avior/Avior.nuspec
  
build:
  project: Avior.sln
  verbosity: normal
  publish_nuget: true

artifacts:
  - path: '**\Avior*.nupkg'
    name: NuGet

deploy:
  provider: NuGet
  api_key:
    secure: WrL2uPCxsKi6WaC+BqV9F6NzgFqtc8P9rtTOrTmcNtVg8YMbbniVxWglwGau0byD
  skip_symbols: true
  artifact: /.*\.nupkg/